version: "3.7"

services:
  etl:
    volumes:
      - ${DB_CONTEXT:-.}/volumes/etl/last_synced_block.txt:/icon-etl/last_synced_block.txt

  postgres:
    volumes:
      - ${DB_CONTEXT:-.}/volumes/postgres:/data/postgres
